const { readFileSync } = require('node:fs');
const { resolve } = require('node:path');
const assert = require('node:assert/strict');
const ts = require('typescript');
const source = readFileSync(resolve(__dirname, '../src/lib/videoWebhook.ts'), 'utf8');
const compiled = ts.transpileModule(source, { compilerOptions: { module: ts.ModuleKind.CommonJS, target: ts.ScriptTarget.ES2021 } }).outputText;
const exported = {};
new Function('exports', compiled)(exported);
const { assertVideoWebhookResponse, videoWebhookAccepted, unconfirmedVideoResponse } = exported;
assert.throws(() => assertVideoWebhookResponse(500, 'Workflow failed'), /HTTP 500.*Workflow failed/);
assert.throws(() => assertVideoWebhookResponse(403, ''), /HTTP 403/);
assert.throws(() => assertVideoWebhookResponse(200, '{"success":false,"message":"Invalid reference"}'), /Invalid reference/);
assert.throws(() => assertVideoWebhookResponse(200, '{"result":{"error":"Magnific rejected request"}}'), /Magnific rejected/);
assert.throws(() => assertVideoWebhookResponse(200, '[{"json":{"status":"failed","message":"No credits"}}]'), /No credits/);
assert.deepEqual(assertVideoWebhookResponse(200, '{"video_url":"https://example.com/video.mp4"}'), { video_url: 'https://example.com/video.mp4' });
assert.equal(videoWebhookAccepted(200, { success: true }), false);
assert.equal(videoWebhookAccepted(200, null), false);
assert.equal(videoWebhookAccepted(200, 'Workflow was started'), false);
assert.equal(videoWebhookAccepted(202, ''), true);
assert.equal(videoWebhookAccepted(200, { result: { status: 'queued' } }), true);
assert.equal(videoWebhookAccepted(200, [{ json: { accepted: true } }]), true);
assert.match(unconfirmedVideoResponse(200, '').message, /Generation is unconfirmed.*empty/);
console.log('Video webhook: HTTP/application errors, nested errors, acceptance and unconfirmed-response checks passed.');
